# Generated by Django 4.2.23 on 2025-08-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='store_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
