# Generated by Django 4.2.23 on 2025-08-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_store_lat_store_lon_alter_address_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card / Apple Pay'), ('cod', 'Cash on Delivery')], default='card', max_length=10),
        ),
    ]
