# Generated by Django 4.2.23 on 2025-08-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
